version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
